name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-reusable-build:
    uses: ai-pipestream/.github/.github/workflows/reusable-service-build.yml@main
    with:
      docker-image-name: opensearch-manager
      dockerfile-path: src/main/docker/Dockerfile.jvm
    secrets: inherit
